using System;
using System.Collections.Generic;
using System.Text;

namespace AzCoreTools.Utilities.Tables
{
    public enum TableErrorCode
    {
        AuthorizationResourceTypeMismatch,
        AuthorizationPermissionMismatch,
        XMethodNotUsingPost,
        XMethodIncorrectValue,
        XMethodIncorrectCount,
        TableHasNoProperties,
        DuplicatePropertiesSpecified,
        TableHasNoSuchProperty,
        DuplicateKeyPropertySpecified,
        TableAlreadyExists,
        TableNotFound,
        ResourceNotFound,
        EntityNotFound,
        EntityAlreadyExists,
        PartitionKeyNotSpecified,
        OperatorInvalid,
        UpdateConditionNotSatisfied,
        PropertiesNeedValue,
        PartitionKeyPropertyCannotBeUpdated,
        TooManyProperties,
        EntityTooLarge,
        PropertyValueTooLarge,
        KeyValueTooLarge,
        InvalidValueType,
        TableBeingDeleted,
        PrimaryKeyPropertyIsInvalidType,
        PropertyNameTooLong,
        PropertyNameInvalid,
        InvalidDuplicateRow,
        CommandsInBatchActOnDifferentPartitions,
        JsonFormatNotSupported,
        AtomFormatNotSupported,
        JsonVerboseFormatNotSupported,
        MediaTypeNotSupported,
        MethodNotAllowed,
        ContentLengthExceeded,
        AccountIOPSLimitExceeded,
        CannotCreateTableWithIOPSGreaterThanMaxAllowedPerTable,
        PerTableIOPSIncrementLimitReached,
        PerTableIOPSDecrementLimitReached,
        SettingIOPSForATableInProvisioningNotAllowed,
        PartitionKeyEqualityComparisonExpected,
        PartitionKeySpecifiedMoreThanOnce,
        InvalidInput,
        NotImplemented,
        OperationTimedOut,
        OutOfRangeInput,
        Forbidden,
    }
}
